--- #YAML:1.0
name:                Text-CSV-Separator
version:             0.19
abstract:            Determine the field separator of a CSV file
license:             perl
author:              
    - Enrique Nell <perl_nell@telefonica.net>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
